
name: solutioning-example-automated-testing

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
      - name: Copy environment example.
        run: cp .env.example .env
      - name: Copy environment connection details.
        run: cp docroot/sites/default/settings.local.php.example docroot/sites/default/settings.local.php
        run: chmod 777 docroot/sites/default/settings.local.php
        run: docker-compose up -d
        run: make installdrupal
        run: make codeck