
name: solutioning-example-automated-testing

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - name: Build the stack
        run: docker-compose up -d
      - name: Test
        run: make codeck