
name: solutioning-example-automated-testing

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: debug file ownership.
        run: ls -la
      - name: Copy environment example.
        run: cp .env.example .env
      - name: Copy environment connection details.
        run: cp docroot/sites/default/settings.local.php.example docroot/sites/default/settings.local.php
      - name: File permissions change.
        run: chomod 777 docroot/sites/default/settings.php
      - name: debug file ownership.
        run: ls -la docroot/sites/default/
      - name: Build the application stack
        run: docker-compose up -d
      - name: Wait for database
        run: sleep 50s
      - name: Install drupal and configuration
        run: make installdrupal
      - name: Test
        run: make codeck