
name: solutioning-example-automated-testing

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
      - name: Copy environment example.
        run: cp .env.example .env
      - name: Build the application stack
        run: docker-compose up -d
      - name: Install drupal and configuration
        run: make installdrupal
      - name: Test
        run: make codeck